server:
  port: 8091
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/wlkg-new
    username: root
    password: wj710723
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 192.168.237.66
    username: wlkg
    password: wlkg
    virtual-host: /wlkg
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: wlkg.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api #  添加路由前缀
  retryable: true
  routes:
  item-service: /item/** #  将商品微服务映射到 /item/**