server:
  port: 8094
spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.237.66
    username: wlkg
    password: wlkg
    virtual-host: /wlkg
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔 5 秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10 秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}
wlkg:
  thymeleaf:
    destPath: G:\apps\nginx-1.12.2\html\item #指定文件路径