server:
  port: 10086
spring:
  application:
    name: wlkg-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: false
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false